---
'172.16.1.1':
  - 'src': '192.168.0.1'
    'dst': '192.168.0.4'
    'via':
      - '192.168.0.2'
      - '192.168.0.3'
      - '192.168.0.4'
    'policy':
      'bandwidth': 0
      'avoid_nodes':
        - ''

'172.16.2.1':
  - 'src': '192.168.0.11'
    'dst': '192.168.0.14'
    'via':
      - '192.168.0.12'
      - '192.168.0.13'
      - '192.168.0.14'
    'policy':
      'bandwidth': 0
      'avoid_nodes':
        - ''
