---
'192.168.0.1':
  '192.168.0.3':
    'via':
     - '192.168.0.3'
    'policy':
      'bandwidth': 0
      'avoid_nodes':
        - '192.168.0.2'

  '192.168.0.4':
    'via':
      - '192.168.0.2'
      - '192.168.0.4'
      - '192.168.0.3'
    'policy':
      'bandwidth': 0
      'avoid_nodes':
        - ''
